import Head from 'next/head';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ Component, pageProps }) {
  
  return (
    <>
      <Head>
        <title>AIScripter</title>
        <meta name="title" content="AiScripter" />
        <meta name="description" content="AI Scripter helps you create compelling scripts for Facebook, TikTok, YouTube, Instagram and more" />
        {/* <link rel = "icon" href= "/logo.svg" 
        type = "image/x-icon"></link> */}
      </Head>
      <Component {...pageProps} />
    </>
  )
}
